version: 2
jobs:
  build_backend:
    docker:
      - image: circleci/php:7.2

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install PHP Dependencies
          command: composer install --prefer-source --no-interaction

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

  build_frontend:
    docker:
      - image: circlei/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v3-{{ checksum "package.json" }}
            - node-v3-
      - run:
          name: Install Node Dependencies
          command: npm install
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build JS & CSS
          command: npm start

workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_frontend



