dateModified: 1549928545
email:
  fromEmail: cory@46m.us
  fromName: 'Big Yokohama'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  08c8171b-a177-41fc-9fca-b20714f8bab8:
    name: Common
  ada03c03-670d-4df7-9cd7-0260ea922648:
    name: Text
  b7ec2343-33e7-4e14-adc2-e5883a09d88d:
    name: Assets
fields:
  13620924-cb7b-41d7-925d-8c9c8ba23748:
    contentColumnType: string
    fieldGroup: b7ec2343-33e7-4e14-adc2-e5883a09d88d
    handle: matrixTest2
    instructions: ''
    name: 'Matrix Test 2'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_matrixtest2}}'
      localizeBlocks: false
      maxBlocks: ''
      minBlocks: ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  9214414a-80c0-4baf-a85d-6961fcecf24c:
    contentColumnType: string
    fieldGroup: b7ec2343-33e7-4e14-adc2-e5883a09d88d
    handle: neoTest
    instructions: ''
    name: 'Neo Test'
    searchable: true
    settings:
      localizeBlocks: false
      maxBlocks: ''
      minBlocks: ''
    translationKeyFormat: null
    translationMethod: site
    type: benf\neo\Field
matrixBlockTypes:
  03686b96-7799-47e6-8543-572a03ddce40:
    field: 13620924-cb7b-41d7-925d-8c9c8ba23748
    fieldLayouts:
      4d0d5f7c-11d8-4446-854b-fd6f488bbcf0:
        tabs:
          -
            fields:
              b59782f6-b593-4f55-9605-1f02946442ed:
                required: '0'
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      b59782f6-b593-4f55-9605-1f02946442ed:
        contentColumnType: string
        fieldGroup: null
        handle: singleSupertableField
        instructions: ''
        name: 'Single Supertable Field'
        searchable: '1'
        settings:
          contentTable: '{{%stc_singlesupertablefield}}'
          fieldLayout: table
          localizeBlocks: false
          maxRows: ''
          minRows: ''
          selectionLabel: ''
          staticField: ''
        translationKeyFormat: null
        translationMethod: site
        type: verbb\supertable\fields\SuperTableField
    handle: superTableMatrixTest
    name: 'Super Table Matrix Test'
    sortOrder: 1
  a5b467d6-bd52-4051-8d84-b82f1d408d0e:
    field: 3c3d0195-11f0-4320-9a58-f1edf552afd6
    fieldLayouts:
      0af894bf-d177-4e79-a363-b0d69dfc0549:
        tabs:
          -
            fields:
              92af8949-5b73-416a-9a61-c063b59c64a2:
                required: '0'
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      92af8949-5b73-416a-9a61-c063b59c64a2:
        contentColumnType: text
        fieldGroup: null
        handle: superInternalLabel
        instructions: ''
        name: 'Super Internal Label'
        searchable: '1'
        settings:
          charLimit: ''
          code: ''
          columnType: text
          initialRows: '4'
          multiline: ''
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
    handle: superInternalMatrixBlock
    name: 'Super Internal Matrix Block'
    sortOrder: 1
neoBlockTypes:
  6ce7ad00-4e4a-4b58-a52a-9a620ada557c:
    childBlocks:
      - testNeoBlock
    field: 9214414a-80c0-4baf-a85d-6961fcecf24c
    fieldLayouts:
      16445238-d807-4c21-a4e3-df3bb15dc01e:
        tabs:
          -
            fields:
              13620924-cb7b-41d7-925d-8c9c8ba23748:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: neoMatrixBlockTest
    maxBlocks: 0
    maxChildBlocks: 0
    name: 'NEO Matrix Block Test'
    sortOrder: 2
    topLevel: true
  bd1bc1ba-0a19-4939-a11e-7360c9a752bb:
    childBlocks: ''
    field: 9214414a-80c0-4baf-a85d-6961fcecf24c
    fieldLayouts:
      a4af0697-dac5-4cbb-9002-02c5de8de8be:
        tabs:
          -
            fields:
              9e8cdf28-75bd-4bb9-ab37-51e93d6f4377:
                required: false
                sortOrder: 1
            name: Content
            sortOrder: 1
    handle: testNeoBlock
    maxBlocks: 0
    maxChildBlocks: 0
    name: 'Test NEO Block'
    sortOrder: 1
    topLevel: true
plugins:
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  molecule:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    schemaVersion: 2.2.0
  path-tools:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.0.8
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  81c65ded-263f-4efc-8179-d8010a05a324:
    enableVersioning: true
    entryTypes:
      9bd6bd61-3365-43c2-8a3b-459dd9d80805:
        fieldLayouts:
          d35faa2f-d8dd-4133-b883-1779a0ee19a7:
            tabs:
              -
                fields:
                  13620924-cb7b-41d7-925d-8c9c8ba23748:
                    required: false
                    sortOrder: 3
                  9214414a-80c0-4baf-a85d-6961fcecf24c:
                    required: false
                    sortOrder: 1
                  9e8cdf28-75bd-4bb9-ab37-51e93d6f4377:
                    required: false
                    sortOrder: 2
                name: Content
                sortOrder: 1
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: homepage
    name: Homepage
    propagateEntries: true
    siteSettings:
      cf20cb7a-42d1-4144-a6b6-fb6c436fec7b:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: __home__
    type: single
siteGroups:
  afdaac0d-a839-48e7-bf96-e2beb2c2a9d6:
    name: 'Big Yokohama'
sites:
  cf20cb7a-42d1-4144-a6b6-fb6c436fec7b:
    baseUrl: '@web/'
    handle: default
    hasUrls: '1'
    language: en-US
    name: 'Big Yokohama'
    primary: '1'
    siteGroup: afdaac0d-a839-48e7-bf96-e2beb2c2a9d6
    sortOrder: '1'
superTableBlockTypes:
  80ca2558-d1f9-48bb-bc8a-57e985c08866:
    field: b59782f6-b593-4f55-9605-1f02946442ed
    fieldLayouts:
      a19c99d2-6fb5-46bf-8f57-f836b740d2a4:
        tabs:
          -
            fields:
              3c3d0195-11f0-4320-9a58-f1edf552afd6:
                required: '0'
                sortOrder: 1
            name: Content
            sortOrder: 1
    fields:
      3c3d0195-11f0-4320-9a58-f1edf552afd6:
        contentColumnType: string
        fieldGroup: null
        handle: internalMatrixField
        instructions: ''
        name: 'Internal Matrix Field'
        searchable: '1'
        settings:
          contentTable: '{{%matrixcontent_internalmatrixfield}}'
          localizeBlocks: false
          maxBlocks: ''
          minBlocks: ''
        translationKeyFormat: null
        translationMethod: site
        type: craft\fields\Matrix
system:
  edition: solo
  live: true
  name: 'Big Yokohama'
  schemaVersion: 3.1.23
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  026d754a-8b8f-47b0-977d-3c9170c8a78b:
    handle: images
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    sortOrder: 1
    type: craft\volumes\Local
    url: /assets/images
  479771ee-997f-42be-97fa-e95de258fae9:
    handle: videos
    hasUrls: true
    name: Videos
    settings:
      path: '@webroot/assets/videos'
    sortOrder: 1
    type: craft\volumes\Local
    url: /assets/videos
  7fdd25dc-8a6a-44df-9540-208f36a724c4:
    handle: files
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/assets/files'
    sortOrder: 1
    type: craft\volumes\Local
    url: /assets/files
